/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as SeasonsRouteImport } from './routes/seasons'
import { Route as DestinationsIndexRouteImport } from './routes/destinations.index'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'
import { Route as DestinationsNewRouteImport } from './routes/destinations.new'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonsRoute = SeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/destinations/$slug',
  path: '/destinations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsNewRoute = DestinationsNewRouteImport.update({
  id: '/destinations/new',
  path: '/destinations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/experiences': typeof ExperiencesRoute
  '/planner': typeof PlannerRoute
  '/seasons': typeof SeasonsRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/destinations/new': typeof DestinationsNewRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/journal/': typeof JournalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/experiences': typeof ExperiencesRoute
  '/planner': typeof PlannerRoute
  '/seasons': typeof SeasonsRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/destinations/new': typeof DestinationsNewRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/destinations': typeof DestinationsIndexRoute
  '/journal': typeof JournalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/experiences': typeof ExperiencesRoute
  '/planner': typeof PlannerRoute
  '/seasons': typeof SeasonsRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/destinations/new': typeof DestinationsNewRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/journal/': typeof JournalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/experiences'
    | '/planner'
    | '/seasons'
    | '/destinations/$slug'
    | '/destinations/new'
    | '/journal/$slug'
    | '/destinations/'
    | '/journal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/experiences'
    | '/planner'
    | '/seasons'
    | '/destinations/$slug'
    | '/destinations/new'
    | '/journal/$slug'
    | '/destinations'
    | '/journal'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/experiences'
    | '/planner'
    | '/seasons'
    | '/destinations/$slug'
    | '/destinations/new'
    | '/journal/$slug'
    | '/destinations/'
    | '/journal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ExperiencesRoute: typeof ExperiencesRoute
  PlannerRoute: typeof PlannerRoute
  SeasonsRoute: typeof SeasonsRoute
  DestinationsSlugRoute: typeof DestinationsSlugRoute
  DestinationsNewRoute: typeof DestinationsNewRoute
  JournalSlugRoute: typeof JournalSlugRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
  JournalIndexRoute: typeof JournalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasons': {
      id: '/seasons'
      path: '/seasons'
      fullPath: '/seasons'
      preLoaderRoute: typeof SeasonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/destinations/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/new': {
      id: '/destinations/new'
      path: '/destinations/new'
      fullPath: '/destinations/new'
      preLoaderRoute: typeof DestinationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ExperiencesRoute: ExperiencesRoute,
  PlannerRoute: PlannerRoute,
  SeasonsRoute: SeasonsRoute,
  DestinationsSlugRoute: DestinationsSlugRoute,
  DestinationsNewRoute: DestinationsNewRoute,
  JournalSlugRoute: JournalSlugRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
  JournalIndexRoute: JournalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
